### ISSUE TITLE
Proxied option instead of DNS only

### ISSUE THREAD

**Issue by deaglenomics** [kissgyorgy/cloudflare-dyndns#12]
Love the project but is it possible to have a variable to toggle between proxied and DNS-only modes?
Currently it defaults to DNS-only mode.

**Comment by deaglenomics** [comment]
Cloudflare API parameter

proxied (boolean)

**Comment by kissgyorgy** [comment]
Sure!

**Comment by kissgyorgy** [comment]
I made a new beta release, let me know if you need any help or if it works for you: https://github.com/kissgyorgy/cloudflare-dyndns/releases/tag/v4.0-beta2

**Comment by deaglenomics** [comment]
Tried it but it looks like its still being overwritted as dns-only.

Command run:
cloudflare-dyndns --proxied --api-token *token-key* domain.net

root@Server~/# cat /root/.cache/cloudflare-dyndns/ip.cache
{"ipv4": {"address": "*ipaddress*", "updated_domains": {"ipaddress": {"zone_id": "*zoneid*", "record_id": "*record-id*", "proxied": true}}}, "ipv6": {"address": null, "updated_domains": {}}}

**Comment by kissgyorgy** [comment]
I fixed the bug, made a new release: https://github.com/kissgyorgy/cloudflare-dyndns/releases/tag/v4.0-beta3

**Comment by deaglenomics** [comment]
Awesome that worked like a charm :)
