### ISSUE TITLE
Specify IP as a parameter

### ISSUE THREAD

**Issue by bindi** [kissgyorgy/cloudflare-dyndns#17]
I don't want to set the DNS to the machine's address I'm running the script from. For my use case I need to be able to set it manually.

**Comment by kissgyorgy** [comment]
Hello,
Thanks for the suggestion, but the whole point of this project is to automatically determine the IP address (that's basically the main feature it provides), that's what Dynamic DNS is about, your use-case is more like "static DNS". You can do that with a simple command line tool which can set the IP for Cloudflare, you don't need this project.  

Something like this: https://github.com/danielpigott/cloudflare-cli  
or a pure shell alternative: https://github.com/bAndie91/cloudflare-cli  

Hope this helps!
