### ISSUE TITLE
Just updates only one A record

### ISSUE THREAD

**Issue by b8engl** [kissgyorgy/cloudflare-dyndns#18]
I have more than one record, but only updates the first one

`cloudflare-dyndns --proxied --api-token **************** domain.pt --force`

**Comment by kissgyorgy** [comment]
What do you mean exactly? One domain can have only one A record. You can specify multiple domains (or subdomains) separately. It intentionally does not update all records for the same zone (zone is the apex domain in Cloudflare terminology).

**Comment by kissgyorgy** [comment]
To put it another way: You don't specify whole Cloudflare zones as the parameters, you need to specify every single domain you want to update one by one.

**Comment by b8engl** [comment]
I have a mail with A record

**Comment by kissgyorgy** [comment]
I have no idea what that means, please elaborate.

**Comment by b8engl** [comment]
At cloudflare, I have 
type `A domain.pt ip Proxied`
type `A mail ip`

If I type `cloudflare-dyndns --proxied --api-token **************** domain.pt --force` I only update the first one

**Comment by b8engl** [comment]
Is there a way to update multiple A records?

**Comment by kissgyorgy** [comment]
So you have two domains. One is the naked (or apex) `domain.pt`, the other is `mail.domain.pt`, which is a subdomain.
Yes, you can update both of those at once like this:  
`cloudflare-dyndns --proxied --api-token **************** domain.pt mail.domain.pt`

**Comment by b8engl** [comment]
No, just `mail` pointing to the `ip`
Can I just add `mail` at the end? 

e.g. `cloudflare-dyndns --proxied --api-token **************** domain.pt mail`

**Comment by kissgyorgy** [comment]
I suggest to learn the basics of DNS first and how Cloudlflare works compared to those. Without that knowledge, it's hard to use tools like this.

When you put a new A record in Cloudflare with a specific **Name** like `mail` in your case, it will be the subdomain of the registered apex domain, which will point to the specified IP address.

Here is an example:
![image](https://user-images.githubusercontent.com/244203/163702762-3211369f-d934-45fb-bbd2-3f683b68220c.png)

In this case, I would have `kissgyorgy.me` with 1.2.3.4 IP address and `mail.kissgyorgy.me` with 2.3.4.5 IP address. They are different domains, `mail.kissgyorgy.me` is a subdomain of `kissgyorgy.me`.

When you have records like this, you have to specify both full domains to this tool like I said before:
`cloudflare-dyndns --proxied --api-token **************** kissgyorgy.me mail.kissgyorgy.me` and it will update both of those records.

**Comment by b8engl** [comment]
Was blind, sorry... yes, subdomain mail.domain.pt

Thanks buddy, for all the help!
