### ISSUE TITLE
macos: document how to get TLS CA certs?

### ISSUE THREAD

**Issue by larham** [kissgyorgy/cloudflare-dyndns#21]
Thanks for the excellent tool, which successfully updated my cloudflare account info.

However, running on macos, certs are missing:

```
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt
```

Can you add to documentation a summary for this, like the following:

---------------------------------------------

For Macos, please provide a certficate CA file something like this:

```
sudo port install curl-ca-bundle # use macports to download CA certs
sudo cp /opt/local/share/curl/curl-ca-bundle.crt   /etc/ssl/certs/ca-certificates.crt
```

**Comment by kissgyorgy** [comment]
Ouch, sorry about that! I try to come up with a more cross-platform way to reference the system-wide CA bundle.

Until that, it's actually configurable: https://github.com/kissgyorgy/cloudflare-dyndns/blob/408dabf4564e53e8f31a18b6aa12bce1d4d039c4/cloudflare_dyndns/ip_services.py#L13-L15
by setting the `REQUESTS_CA_BUNDLE` environment variable.

**Comment by larham** [comment]
That's a convenient config, thanks.

In this case, I'm not sure about a perfect cross platform solution since Macos [does not have a file-based approach](https://stackoverflow.com/questions/24675167/ca-certificates-mac-os-x) (certs are held inside a "Keychain")

However, I think it would be nicely cross-platform to test for the existence of certs, and complain with a nice message that is perhaps a URL to your docs (which can change more rapidly than releases).

For Macos, there is a step where the certs need to be downloaded somehow into a .crt (or .pem??) file. That is the first line of my original suggestion.

Thanks again for the tool and its support.

**Comment by kissgyorgy** [comment]
Thanks for the info! I might be able to solve that by using a new Python library https://github.com/sethmlarson/truststore
which has been created for this exact problem.

No promises, but would you test a beta release if I implement this? I don't have access to a Mac.

**Comment by larham** [comment]
Oh, that's a fancy library. 

Yes, I'd be happy to test a future release on Macos. A follow-up comment here should reach me in a "push" fashion, and feel free to use other channels.

**Comment by kissgyorgy** [comment]
I made a new release: https://github.com/kissgyorgy/cloudflare-dyndns/releases/tag/v5.0beta1
Let me know if this works for you.

**Comment by larham** [comment]
Thanks, can you help me a little with testing?  The binary for linux does not work on macos.  Is it possible to compile a binary for macos from your workstation, or does that require compilation on the target architecture?  

I downloaded the source and attempted to run the CLI below.  If I need to test from source, what am I doing wrong below? 

```
❯ cd cloudflare-dyndns-5.0beta2
direnv: loading ~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2/.envrc
Installing virtualenv for Python 3.10.6
direnv: ([/usr/local/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
Activating Python 3.10.6 virtualenv
Virtualenv has been activated for Python 3.10.6
~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2/.venv/bin/python
direnv: export +VIRTUAL_ENV +VIRTUAL_ENV_PROMPT ~PATH
❯ poetry install
Installing dependencies from lock file

Package operations: 35 installs, 0 updates, 0 removals

  • Installing idna (3.3)
  • Installing lazy-object-proxy (1.7.1)
  • Installing parso (0.8.3)
  • Installing sniffio (1.2.0)
  • Installing wrapt (1.14.1)
  • Installing anyio (3.6.1)
  • Installing astroid (2.12.2)
  • Installing certifi (2022.6.15)
  • Installing h11 (0.12.0)
  • Installing isort (4.3.21)
  • Installing jedi (0.18.1)
  • Installing mccabe (0.6.1)
  • Installing pyparsing (3.0.9)
  • Installing appdirs (1.4.4)
  • Installing attrs (21.4.0)
  • Installing click (7.1.2)
  • Installing httpcore (0.15.0)
  • Installing iniconfig (1.1.1)
  • Installing packaging (21.3)
  • Installing pathspec (0.9.0)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing pylint (2.4.1)
  • Installing pylint-starlark-plugin (1.0.2)
  • Installing regex (2022.7.25)
  • Installing rfc3986 (1.5.0)
  • Installing toml (0.10.2)
  • Installing typed-ast (1.5.4)
  • Installing typing-extensions (4.3.0)
  • Installing black (19.10b0)
  • Installing httpx (0.23.0)
  • Installing pydantic (1.9.2)
  • Installing pylint-starlark (1.1)
  • Installing pytest (6.2.5)
  • Installing truststore (0.4.0)

Installing the current project: cloudflare-dyndns (5.0beta2)
❯ ls
Dockerfile        LICENSE           cloudflare_dyndns pyoxidizer.bzl    requirements.txt
Justfile          README.md         poetry.lock       pyproject.toml    tests
❯ ./cloudflare_dyndns/cli.py
Traceback (most recent call last):
  File "~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2/./cloudflare_dyndns/cli.py", line 3, in <module>
    from pathlib import Path
  File "~/.pyenv/versions/3.10.6/lib/python3.10/pathlib.py", line 1, in <module>
    import fnmatch
  File "~/.pyenv/versions/3.10.6/lib/python3.10/fnmatch.py", line 14, in <module>
    import re
  File "~/.pyenv/versions/3.10.6/lib/python3.10/re.py", line 124, in <module>
    import enum
  File "~/.pyenv/versions/3.10.6/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2/cloudflare_dyndns/types.py", line 1, in <module>
    import ipaddress
  File "~/.pyenv/versions/3.10.6/lib/python3.10/ipaddress.py", line 14, in <module>
    import functools
  File "~/.pyenv/versions/3.10.6/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2/cloudflare_dyndns/types.py)
```

**Comment by kissgyorgy** [comment]
There is a shell script installed in the virtualenv called `cloudflare-dyndns`. From an activated virtualenv, you should be able to run that. Otherwise: `poetry run cloudflare-dyndns` or `poetry shell; cloudflare-dyndns`

**Comment by larham** [comment]
It seemed to work, thanks!

```
❯ mv ~/.cache/cloudflare-dyndns/ip.cache /tmp
❯ sudo mv /etc/ssl/certs/ca-certificates.crt /tmp
❯ mv .venv /tmp/
❯ cd ..
❯ cd -
~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2
direnv: loading ~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2/.envrc
Installing virtualenv for Python 3.10.6
direnv: ([/usr/local/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
Activating Python 3.10.6 virtualenv
Virtualenv has been activated for Python 3.10.6
~/workspace/testclouddynddns/cloudflare-dyndns-5.0beta2/.venv/bin/python
direnv: export +VIRTUAL_ENV +VIRTUAL_ENV_PROMPT ~PATH
❯ ./.venv/bin/cloudflare-dyndns  --api-token y5nVWaIsNNt79QM_pCA4UINa_jpqn4kpMmzPHv2d www.codegild.com
zsh: no such file or directory: ./.venv/bin/cloudflare-dyndns
❯ poetry install
Installing dependencies from lock file

Package operations: 35 installs, 0 updates, 0 removals

  • Installing idna (3.3)
  • Installing lazy-object-proxy (1.7.1)
  <snip>
  • Installing pytest (6.2.5)
  • Installing truststore (0.4.0)

Installing the current project: cloudflare-dyndns (5.0beta2)
❯ ./.venv/bin/cloudflare-dyndns  --api-token <snip>
Domains to update: <snip>
Loading cache from: ~/.cache/cloudflare-dyndns/ip.cache

Checking current IPv4 address with service: CloudFlare IPv4 trace (https://1.1.1.1/cdn-cgi/trace)
<snip>
Updating <snip> A record.

Saving cache to: ~/.cache/cloudflare-dyndns/ip.cache

Done.
```

**Comment by kissgyorgy** [comment]
Great!
But you accidentally leaked the domain and API token!

**Comment by kissgyorgy** [comment]
> Is it possible to compile a binary for macos from your workstation, or does that require compilation on the target architecture

It's not possible to cross-compile it with PyOxidizer yet, but you can use the Docker image: https://hub.docker.com/repository/docker/kissgyorgy/cloudflare-dyndns

**Comment by larham** [comment]
Thanks, I added one more "snip", and I'll recycle that token now :)
