### ISSUE TITLE
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt

### ISSUE THREAD

**Issue by kurtxie** [kissgyorgy/cloudflare-dyndns#24]
After pip install cloudflare-dydns in CENT-OS 7.9, and running the program with cloudflare api-token, then I got the error message:
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/ca-certificates.crt

**Comment by kissgyorgy** [comment]
This has been already fixed in v5.0, but I did not make a relase yet. Would you try if v5.0 beta2 works for you?
https://github.com/kissgyorgy/cloudflare-dyndns/releases/tag/v5.0beta2
