### ISSUE TITLE
cache is overwritten even when not changed

### ISSUE THREAD

**Issue by cu** [kissgyorgy/cloudflare-dyndns#25]
This is a very nice tool, thank you! I hope to use it to replace my own home-grown version of roughly the same thing.

One thing I noticed is that the cache file `~/.cache/cloudflare-dyndns/ip.cache` gets overwritten on every invocation of the program, even if nothing has changed. It's just a few hundred bytes, yes, but on flash storage this equates to at least a 4kB or more write depending on the hardware and filesystem. In the grand scheme of things, very likely not a big deal, but it would be nice to do the right thing if possible.

I haven't had the time to fully understand the flow of things, but two approaches that I can think of:

1. Track changes to the cache somehow and mark the cache as "dirty" when a value is written. Then, only write when the cache is dirty.
2. Before writing the cache file, read the existing file and compare the JSON. Only trigger a write when they differ.

One workaround for those who are concerned about unnecessary writes could be to store the cache file on a RAM-backed filesystem, e.g. `/dev/shm/ip.cache`.

**Comment by kissgyorgy** [comment]
You are right. I fixed it: https://github.com/kissgyorgy/cloudflare-dyndns/releases/tag/v5.0beta3
You can install with pip: `pip install cloudflare-dyndns==5.0b3`
