### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by Tuinslak** [kissgyorgy/cloudflare-dyndns#3]
It currently only updates A records. 

If IPv6 is detected it woud be nice if it updated the AAAA record as well (if IPv6 is not detected and an AAAA record exists, it should be cleared). 

Thanks

**Comment by kissgyorgy** [comment]
Can you test which services from the listed IP_SERVICES can return an IPv6 address? https://github.com/kissgyorgy/cloudflare-dyndns/blob/4cd03bc1200378b4509d73bd993c000b491c9700/cloudflare_dyndns.py#L50-L77
and copy examples here? I don't have access to a network which has IPv6 only.

**Comment by Tuinslak** [comment]
Sure. From that list only ifconfig.co:

```
$ curl -6 https://ifconfig.co/ip
2404:e801:200e:48c:40f0:ce0b:e57d:8c0b
```
All the other ones return the public IPv4 address.

I know ifconfig.co is not always reliable (i.e. you get hit by rate-limiting superfast, max one request/min or something). 

icanhazip.com could be another alternative:

```
$ curl -6 icanhazip.com
2404:e801:200e:48c:40f0:ce0b:e57d:8c0b
```

**Comment by kissgyorgy** [comment]
I just deleted ifconfig.co from the list, it never works for me.

What does https://1.1.1.1/cdn-cgi/trace return for you?

As currently implemented, I'm just iterating through the list, starting with the first, and only using any other service if the first failed. If the cloudflare one doesn't return IPv6, it means it should be configurable.

Or does it return invalid data for you?

**Comment by Tuinslak** [comment]
Cloudflare only seems to return IPv4 address:

```
$ curl https://1.1.1.1/cdn-cgi/trace
fl=35f756
h=1.1.1.1
ip=58.96.209.56
ts=1616234498.228
visit_scheme=https
uag=curl/7.64.1
colo=SIN
http=http/2
loc=SG
tls=TLSv1.2
sni=off
warp=off
gateway=off
$ curl -6 https://1.1.1.1/cdn-cgi/trace
fl=35f371
h=1.1.1.1
ip=58.96.209.56
ts=1616234506.68
visit_scheme=https
uag=curl/7.64.1
colo=SIN
http=http/2
loc=SG
tls=TLSv1.2
sni=off
warp=off
gateway=off
```

**Comment by kissgyorgy** [comment]
Hmm. Maybe it could be done with an option, similar to how curl does it, and in case that option is enabled, only those IP services would be selected which actually use IPv6.

But in order to do that, I would need to have at least 3 IP services which supports IPv6 to make it reliable. Can you find me another 2?

**Comment by Tuinslak** [comment]
## IPv4

Found this one for IPv4: http://whatismyip.akamai.com -- I assume Akamai is a trustworthy provider. 

## For IPv6:

### Using DNS requests (using for example `dig` you could add `-4` or `-6`):
```
$ dig -6 @ns1.google.com TXT o-o.myaddr.l.google.com +short
"2404:e801:200e:48c:81e4:aaa9:fafa:1549"
```
### Using curl:

ip.tyk.nu: 
```
$ curl https://ip.tyk.nu/ -6
2404:e801:200e:48c:81e4:aaa9:fafa:1549
```
wgetip.com:
```
$ curl https://wgetip.com/ -6
2404:e801:200e:48c:81e4:aaa9:fafa:1549%
```
whatismyipaddress.com:
```
$ curl https://bot.whatismyipaddress.com -6
2404:e801:200e:48c:81e4:aaa9:fafa:1549%
```

I found a list here: https://unix.stackexchange.com/questions/22615/how-can-i-get-my-external-ip-address-in-a-shell-script

**Comment by kissgyorgy** [comment]
Why do you say:
> "if IPv6 is not detected and an AAAA record exists, it should be cleared"

Does your provider change IP address type from time to time?

I'm asking because I'm thinking about a command line flag `-6` which would change `AAAA` record type only and leave `A` records alone. This would work similarly to other tools like `dig` and `curl`.

**Comment by Tuinslak** [comment]
Ah -- I was looking for a solution that I can deploy on various boxes scattered across Europe at customer's sites and having the (last known) IP would be useful if something went wrong and the device went down. Having the device autodetect if it has IPv6 and, if yes, add that one as well, would have been easy.

Ofc I could just test it in a script or something:

```
IPV6=`ping6 -c 1 google.com >/dev/null 2>&1 ; echo $?`
if [ "$IPV6" = "0" ]
then
	curl -6 https://ifconfig.co 2>/dev/null
else
	echo "** IPv6 not reachable **"
fi
```

**Comment by kissgyorgy** [comment]
Hmm, very interesting use-case! I don't understand the "as well" part. Is it possible for the device to have both IPv4 and IPv6 addresses and would you like to set them both `A` and `AAAA` records in that case?
Or how should it work?

**Comment by Tuinslak** [comment]
Yes -- correct. In my case, I'd like to get as much information as possible (just in case). So device.domain.tld would have both an A and AAAA DNS record if it has both an IPv4 and IPv6 address.

**Comment by kissgyorgy** [comment]
Is this how it should work?
- only IPv4 detected: `A` record is set, `AAAA` is cleared.
- only IPv6 detected: `AAAA` record is set, `A` is cleared.
- both IPv4 and IPv6 detected: `A` and `AAAA` records are set.

The problematic part: how to detect both IPv4 and IPv6 addresses? As I understand so far, every IP service would only give one address back, depends on which IP did you get there.
So we should make two requests at least somehow for IPv4 and one for IPv6, but that one only for those which can handle IPv6 addresses.

Not sure how to make this work without breaking the simple case (IPv4 only).

**Comment by kissgyorgy** [comment]
What if I still make the `-6` option, but also add a `-4` (which would be turned ON by default). There would be no deleting of the other records in this case, just updating the related `A` or `AAAA` record.

**Comment by Tuinslak** [comment]
Perhaps, to avoid too much logic in the script, you could add a `-d` flag to delete the existing A or AAAA record (`-d -6`)? Then the bash script could simply delete the AAAA record if it exists and no IPv6 is detected. 

But sure, a -4 (or -A) or -6 (-AAAA) option would work. Deleting can probably be handled elsewhere. 

A script could do something along the lines of:
```
IPv4=`curl -s --connect-timeout 10 -4 icanhazip.com 2>/dev/null` 
IPv6=`curl -s --connect-timeout 10 -6 icanhazip.com 2>/dev/null` || true # true needed in case IPv6 is not detected and curl would crash the script
update-cf.sh -A $IPv4 -d some.domain.tld
update-cf.sh -AAAA $IPv6 -d some.domain.tld
```

**Comment by kissgyorgy** [comment]
I was thinking about this and I think I got it. There would be one new variable, let's call it `ip_mode` or something, which could have three possible values:
- `4` (the default) which would only deal with IPv4 capable detection services and leave IPv6 addresses alone.
- `6` would work the same way as `4`, but for IPv6 addresses.
- `auto4or6` would do the function you need (detect both, delete the other what found).

So you would only need to set the `auto4or6` for your use-case.

**Comment by Tuinslak** [comment]
Sounds good :)

**Comment by kissgyorgy** [comment]
Man, you have no idea who big a rabbit hole you sent me down with this. 😄 
One more question: `auto4or` (let's call it `either`) would ever be a use case?
I mean, if the machine has both public IPv4 and IPv6 addresses, you ALWAYS want to set them both, right?

**Comment by Tuinslak** [comment]
;) maybe my usecases are quite particular and I am honestly not really sure if anyone else has benefit for this. So don’t worry too much about it if it’s too hard or messy to accomplish. I can’t find another method of doing it :) 

In my case, my devices always have IPv4 and sometimes IPv6. And I would indeed want to set them both (even if you don’t end up using, say, the IPv6 address, it’s good to have it, just in case). 

There are some networks that are moving to IPv6 only, and that’s especially useful for IoT and other devices, so you can reach/ping/connect to eachother using DNS but in the same network (ipv device###.iot.domain.tld could map to an IPv6 only)

**Comment by kissgyorgy** [comment]
Here is very similar idea for the `-4` and `-6` options. The `curl` and `dig` implementations confused me (I straced them), but those are totally different for our use-cases, because curl or dig only have to use one network at a time, BUT this script might need them, so if I make them a turn-on / turn off option, like:
`--4` / `--no-4` and
`--6` / `--no-6`, 
it would be more obvious and simple and the `--delete-missing` option would delete `A` records when IPv4 is missing and `AAAA` when IPv6 is missing, not the "delete the other if this is set" way. I think it would be the easiest to understand for the users. MAYBE 😄

**Comment by kissgyorgy** [comment]
Here is what I'm thinking:

```
Usage: cloudflare-dyndns-ipv6-draft.py [OPTIONS] [DOMAINS]...

  A command line script to update CloudFlare DNS A and/or AAAA records based
  on the current IP address(es) of the machine running the script.

  For the main domain (the "@" record), simply put "example.com"
  Subdomains can also be specified, eg. "*.example.com" or "sub.example.com"

  You can set the list of domains to update in the CLOUDFLARE_DOMAINS
  environment variable, in which the domains has to be separated by
  whitespace, so don't forget to quote the value!

  The script supports both IPv4 and IPv6 addresses. The default is to set
  only A records for IPv4, which you can change with the relevant options.

Options:
  --api-token TEXT   CloudFlare API Token (You can create one at My Profile
                     page / API Tokens tab). Can be set with
                     CLOUDFLARE_API_TOKEN environment variable.  [required]

  -4 / -no-4         Turn on/off IPv4 detection and set A records. [default:
                     on]

  -6 / -no-6         Turn on/off IPv6 detection and set AAAA records.
                     [default: off]

  --delete-missing   Delete A records when no IPv4 address can be detected,
                     delete AAAA record in case of IPv6.

  --cache-file FILE  Cache file  [default: ~/.cache/cloudflare-dynds/ip.cache]
  --force            Delete cache and update every domain
  --debug            More verbose messages and Exception tracebacks
  --help             Show this message and exit.
```

So you would use `cloudflare-dynds -4 -6 --delete missing`, which means, theoretically IPv4 could be deleted, but in practice I don't expect that to happen for the foreseeable future.

**Comment by Tuinslak** [comment]
sounds good :)

**Comment by kissgyorgy** [comment]
Man, this is insane. I'm almost ready, but not sure I will make a release at the end. The world is not ready for IPv6 yet.

**Comment by Tuinslak** [comment]
IPv6 is the future ;) But if it's too complicated that's okay -- no expectations here!

**Comment by kissgyorgy** [comment]
I made a beta release: https://github.com/kissgyorgy/cloudflare-dyndns/releases/tag/v4.0-beta

Would you test it? Especially looking for IPv6 is working correctly, as I can't really test it on multiple machines.

**Comment by jotoho** [comment]
```
./cloudflare-dyndns-linux-x86-4.0-beta: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./cloudflare-dyndns-linux-x86-4.0-beta)
```

Wanted to try running that binary on a Debian 10 cloud vm but Debian 10 only provides [`libc-bin`](https://packages.debian.org/stable/libc-bin) version 2.28 and your build apparently needs 2.29.

This feature seems interesting and I could use a better way of updating the Cloudflare DNS records that point to my home network than my shoddy self-written shell script so I'll keep an eye on this project.

**Comment by kissgyorgy** [comment]
I need to build with an older libc..

**Comment by Tuinslak** [comment]
I may be going crazy (sorry, a lot of random stuff going on, can't really think too straight):

On Debian:
```
yeri@box /tmp $ ./cloudflare-dyndns-linux-x86-4.0-beta
zsh: exec format error: ./cloudflare-dyndns-linux-x86-4.0-beta
yeri@box /tmp $ bash cloudflare-dyndns-linux-x86-4.0-beta
cloudflare-dyndns-linux-x86-4.0-beta: cloudflare-dyndns-linux-x86-4.0-beta: cannot execute binary file
yeri@box /tmp $ python3 ./cloudflare-dyndns-linux-x86-4.0-beta
  File "./cloudflare-dyndns-linux-x86-4.0-beta", line 1
SyntaxError: Non-UTF-8 code starting with '\x98' in file ./cloudflare-dyndns-linux-x86-4.0-beta on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by kissgyorgy** [comment]
```
$ chmod +x cloudflare-dyndns-linux-x86-4.0-beta
$ cloudflare-dyndns-linux-x86-4.0-beta
```

**Comment by Tuinslak** [comment]
Yea, definitely did that:

```
yeri@box /tmp $ chmod +x cloudflare-dyndns-linux-x86-4.0-beta
yeri@box /tmp $ ./cloudflare-dyndns-linux-x86-4.0-beta
zsh: exec format error: ./cloudflare-dyndns-linux-x86-4.0-beta
```

**Comment by kissgyorgy** [comment]
Maybe it did not download properly? What does `curl -SsL https://github.com/kissgyorgy/cloudflare-dyndns/releases/download/v4.0-beta/cloudflare-dyndns-linux-x86-4.0-beta.sha256 | sha256sum --check` say?

**Comment by Tuinslak** [comment]
cloudflare-dyndns-linux-x86-4.0-beta: OK

**Comment by Tuinslak** [comment]
oh wait -- this is amd64 only ?

**Comment by kissgyorgy** [comment]
I uploaded wheels, which you can download and install with pip

**Comment by kissgyorgy** [comment]
This is working since v4.0-beta, let me know if you have any problem with it!

**Comment by Tuinslak** [comment]
Thanks! :)
